global using Xunit;
global using Moq;
global using FluentAssertions;
global using AutoFixture;
global using AutoFixture.Xunit2;
global using Microsoft.Extensions.Logging;
global using AutoMapper;
global using Domain.Entities;
global using Domain.Interfaces.Repositories;
global using Model.Models;
global using Model.RequestModels;
global using Model.Enums;
global using Service.Interfaces;
global using Service.Implementations;
global using Repository.Implementations;
global using LegacyOrder.Tests.TestFixtures;
global using Microsoft.Extensions.DependencyInjection;
global using Common.Exceptions;

